version: '3'
services:
  db:
    image: postgres
  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - './server:/code'
    ports:
      - "8000:8000"
    depends_on:
      - db
  # client:
  #   container_name: client
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   command: npm start
  #   volumes:
  #     - './client:/code'
  #   ports:
  #     - '8080:8080'