version: '3'
services:
  db:
    image: postgres
  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - './server/:/usr/code'
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client/:/usr/code'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development